### ISSUE TITLE
TODO List for SimpleFramework version 2.0

### ISSUE THREAD

**Issue by PeratX** [iTXTech/SimpleFramework#2]
- [ ] High performance socket support (maybe swoole)
- [x] Support for PHP 7.2
- [x] Single Thread mode

**Comment by PeratX** [comment]
SimpleFramework is a HIGH PERFORMACE command line framework.
So it only supports the latest stable version of PHP.
Legacy PHP 7.0 & PHP 7.1 support is located [here](https://github.com/iTXTech/SimpleFramework/tree/php-7.0).
