### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PeratX** [iTXTech/SimpleFramework#3]
# SimpleFramework is now marked as `DEPRECATED `and in `maintaince mode`

After 6 years of intermittent development (2016-2022), iTX Technologies has decided to sunset the project.

No new features will be implemented, but bug fixes will continue to be available.

# 2.1 - Release before `01/31/2019`
## Feature Freeze  `12/09/2018`

- [x] Add `autoload.php` for single script that using `SimpleFramework`
- [x] Add `StringUtil`
- [x] Extensible Command Options `namespace iTXTech\SimpleFramework\Console\Option`
- [x] Improve Log Level and add config entry in `config.json`
- [x] Improve `ConsoleReader`
- [x] Improve `Curl` APIs

## Notes

* `Command Options` is based on `apache commons cli`

# 2.1.x - Bug fix & Beta features
- [x] Module HotPatch (Beta)

# 2.2 - Release before `12/31/2019`

- [ ] ~~Change license to `APL 2.0` or `LGPL 3.0`~~ - Cancelled
- [ ] ~~Introduce some `PHP 7.3` features~~ - Cancelled
- [ ] ~~Add `PSR-4` autoloader~~ - Cancelled
- [x] Module HotPatch
- [x] Preload Feature
- [x] Optimize Command Line Options API
- [x] Autoload, SFLoader, Customized stub.php
- [x] Support sf.json
- [x] Rewrite module load order (remove `order` in `sf.json`)
- [x] Compatible with Composer

# 2.2.1 - Released `05/10/2020`

- [x] Some Windows APIs for PHP 7.4
- [x] Final version supports PHP 7.2
- [x] New Swoole Coroutine Logger

# 3.0 - Draft

- [ ] Design for [PHP 8.0](https://wiki.php.net/todo/php80) which means it will not be compatible with 7.x
  - [ ] Typed varibles and methods, introduce `mixed` and `union`
  - [ ] Introduce `annotations`
  - [ ] New multi-threading model ~~(maybe)~~
- [ ] Optimize for [PeachPie](https://www.peachpie.io/)
- [ ] OS Platform APIs `iTXTech\SimpleFramework\Util\Platform`
  - [x] Windows
  - [ ] Linux
  - [ ] macOS

# Something else

- [x] Provide `SimpleFramework` customized `php-build-scripts`
- [x] Provide pre-built php binary for `Windows`
- [ ] Provide pre-built php binary for Linux `ARMv7/AArch64`

# Goal

* Keep `SimpleFramework.phar` as light as possible.
* Framework itself and Modules release in `PHAR` format

## [SF 2.2 Features (Chinese)](https://peratx.net/index.php/2019/10/06/simpleframework-2-2-0-features.html)

**Comment by iPocket** [comment]
For that commit, I was about to make a pull request but due to the long time I haven't used GitHub in I accidentally pushed it directly. I see you got some PMMP SPL there, that's fine.

**Comment by PeratX** [comment]
You are welcome.
